name: 'OAK9 Github Action'
description: 'OAK9 Github Action'
environment: production
inputs:
  organizationId:
    description: 'Organization ID'
    required: true
    default: 'inspire11'
  projectId: # id of project
    description: 'Project ID'
    required: true
    default: 'proj-inspire11-1'
  maximumSeverity:
    description: 'Maximum severity'
    required: true
    default: 'critical'
  logDesignGaps:
    description: 'A boolean flag that notes if design gaps should be displayed in GitHub Workflow console'
    default: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'activity'
  color: 'orange'
